interface.h/cpp: change function names according to used classes
atlas-engineer/cl-webengine pull request #6
Opened 2021-01-18 14:28 UTC by unit4096

This fixes ambiguity in function names by renaming them according to wrapped classes.

#### Motivation

Some wrapper function names do not describe Qt objects inside them.

The example below shows a function with a name starting from "window" but using an instance of `QWidget` class:
``` cpp
void windowSetWindowTitle(void* window, char* title) {
    QWidget *_window = reinterpret_cast<QWidget*>(window);
    _window->setWindowTitle(title);
}
```

The change of function names now helps avoid ambiguity later, for example, in implementing wrapper functions for methods of `QWindow` class.

2021-01-18 17:31 UTC, aartaka requested changes
Can you please rename arguments (`void *window` to `void *widget`) and automatic variable names (`_window` to `_widget`) too in the renamed functions, so that these won't go out of sync with function names?

Looks good otherwise. Once you rename variables and arguments, I'll bind the CL side and we can merge. 

@jmercouris, does this rename require version bumping? If so, maybe we can wait a bit and discuss a bigger renaming, like switching to `snake_case` that `cffi` understands natively.

2021-01-18 19:11 UTC, unit4096 commented
>Can you please rename arguments (void *window to void *widget) and automatic variable names (_window to _widget) too in the renamed functions, so that these won't go out of sync with function names?

Good point! Sure, I will rename the arguments and the variable names.

2021-01-18 19:27 UTC, aartaka commented
The last commit should be a part of the first one. Can you squash these?

2021-01-25 16:40 UTC, Ambrevar commented
Looks good to me!
@jmercouris Thoughts about this?

2021-01-25 16:42 UTC, Ambrevar commented
About the version bump, we don't have any tag yet, and the .asd says "0.0", so it seems to me this is a complete alpha with zero guarantee :)
We can bump the version when the code starts stabilizing I think.

2021-01-25 16:54 UTC, jmercouris commented
I've already discussed with Artyom, looks OK!

2021-01-26 09:19 UTC, aartaka commented
@unit4096, I've modified your commit because `windowIsActiveWindow` was `extern`-ed instead of `widgetIsActiveWindow`.

-------------------------------------------
Lisp-side bindings for renamed functions are there!

@Ambrevar, @jmercouris, anything else we should do before merging? Seems merge-able. It compiles on my machine at least xD

2021-01-26 09:19 UTC, aartaka approved these changes

2021-01-26 09:56 UTC, merged

2021-01-26 09:56 UTC, Ambrevar commented
Thank you very much! :)

2021-01-26 09:57 UTC, Ambrevar commented
Thank you very much! :)